### ISSUE TITLE
Publish to central Maven repository

### ISSUE THREAD

**Issue by ktuszek** [nomalab/subtitle#64]
Hello!

This is really nice and useful project, thanks!

Have you thought of pushing the latest changes to the central Maven repository? You've done a couple of fixes recently but last version in Maven is from 2021.

**Comment by lealceldeiro** [comment]
I'd be happy to help with whatever's needed to push the latest changes to maven central, @Romanelaf, @ktuszek

**Comment by Romanelaf** [comment]
Hello,
Sorry for the delay!
I just released version 1.2.3, it will be available soon on Central. I'll make sure to push the next releases from now on.
Let me know if there is anything else.
